WIDTH, HEIGHT = 1280, 720
FRAMERATE = 60

SCORE_FONT_SIZE = 40

ROCKET_SPEED = 3
ROCKET_ROTATION_SPEED = 2
ROCKET_SIZE_SCALE = 1.6

METEOR_SPAWN_CHANCE = 0.05  # per frame
METEOR_SPAWN_PADDING = 20   # distance from display border
METEOR_SPEED = 3
METEOR_SIZE_SCALE = 1.8